spring:
  application:
    name: CConnet
  data:
    mongodb:
      uri: ${MONGODBURI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${CORREO_JMAIL}
    password: ${PASSWD_JMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}